from widgets.splitter import Splitter
from widgets.toolBar import ToolBar
from widgets.menuBar import MenuBar
from widgets.statusBar import StatusBar
from widgets.treewidget import TreeWidget
from widgets.firstPage import FirstPage
from widgets.lastPage import LastPage
from widgets.toolBox import ToolBox
from widgets.menu import *
from widgets.settings import *